export const SHOWLOADING = "SHOWLOADING"
export const HIDELOADING = "HIDELOADING"

export const BLACKHEADERISTRUE = 'BLACKHEADERISTRUE'
export const BLACKHEADERISFALSE = 'BLACKHEADERISFALSE'
export const GREENHEADERISTRUE = 'GREENHEADERISTRUE'
export const GREENHEADERISFALSE = 'GREENHEADERISFALSE'

export const SHOWLOADING_SUCCESS = "SHOWLOADING_SUCCESS"
export const HIDELOADING_SUCCESS = "HIDELOADING_SUCCESS"

export const BLACKHEADERISTRUE_SUCCESS = 'BLACKHEADERISTRUE_SUCCESS'
export const BLACKHEADERISFALSE_SUCCESS = 'BLACKHEADERISFALSE_SUCCESS'
export const GREENHEADERISTRUE_SUCCESS = 'GREENHEADERISTRUE_SUCCESS'
export const GREENHEADERISFALSE_SUCCESS = 'GREENHEADERISFALSE_SUCCESS'

export const ALLHEADERISFALSE = 'ALLHEADERISFALSE'
export const ALLHEADERISFALSE_SUCCESS = 'ALLHEADERISFALSE_SUCCESS'
